name: Deployment Ejercicio 2 Laboratorio Cloud

on:
  push:
    branches:
      - master

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v2
      - name: Uses SSH Key
        run:  |
          mkdir -p ~/.ssh/
          echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/id_rsa
          sudo chmod 600 ~/.ssh/id_rsa
      - name: Git user config
        run: |
          git config --global user.email "manuel.a.espejo@gmail.com"
          git config --global user.name "manang77"
      - name: Dependencies install
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy
        run: npm run deploy -- -r git@github.com:manang77/Laboratorio-Cloud-2.git

